# Generated by Django 5.1 on 2024-08-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='qbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='api/images')),
                ('answer', models.CharField(max_length=20)),
                ('qtype', models.CharField(max_length=20)),
            ],
        ),
    ]
