# Generated by Django 5.1 on 2024-08-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qbank',
            name='image',
            field=models.ImageField(null=True, upload_to='api/images'),
        ),
    ]
